name: Decrypter
title: Decrypter
description: JavaScript Deobfuscator and Unpacker
version: 1.11.1
author: Zzbaivong
author_email: Zzbaivong@gmail.com
url: https://teachwiki.github.io
baseurl: /Decrypter
repository: teachwiki/Decrypte
license: MIT

theme: jekyll-theme-hacker
show_downloads: false
google_analytics: 
sass:
  style: compressed

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "package.json",
    "package-lock.json",
    "Dockerfile",
    "docker-compose.yml",
    "docker-entrypoint.sh",
    "workbox-config.js"
  ]
incremental: false

environment: production
